name: visinity
channels:
  - conda-forge
dependencies:
  - python=3.8
  - Flask=2.1.0
  - flask-sqlalchemy
  - hdbscan
  - nomkl
  - numpy
  - orjson
  - pandas
  - pillow=8.1.1
  - requests
  - scikit-learn
  - scikit-image
  - scipy
  - tifffile=2021.4.8
  - umap-learn
  - waitress
  - zarr=2.10.1
  - pyinstaller
  - pip
  - pip:
      - elementpath==2.3.2
      - KDEpy
      - llvmlite
      - numba
      - numpy-indexed
      - ome-types==0.2.0
      - opencv-python
      - xmlschema==1.8.0

